using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Simulates weapon sway based on mouse input.
/// </summary>
public class WeaponSway : MonoBehaviour
{
	[Header("Sway Settings")]
	[SerializeField] private float smooth; // Smoothing factor for sway movement.
	[SerializeField] private float swayMultiplier; // Multiplier for mouse input to control sway intensity.

	// Start is called before the first frame update
	void Start()
	{
		// Initialization code if needed
	}

	// Update is called once per frame
	void Update()
	{
		float mouseX = Input.GetAxisRaw("Mouse X") * swayMultiplier;
		float mouseY = Input.GetAxisRaw("Mouse Y") * swayMultiplier;

		Quaternion rotationX = Quaternion.AngleAxis(-mouseY, Vector3.right);
		Quaternion rotationY = Quaternion.AngleAxis(mouseX, Vector3.up);

		Quaternion targetRotation = rotationX * rotationY;

		transform.localRotation = Quaternion.Slerp(transform.localRotation, targetRotation, smooth * Time.deltaTime);
	}
}
